"""Initial migration

Revision ID: ebbadcc841c9
Revises: 
Create Date: 2025-08-05 02:44:05.394618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbadcc841c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', name='estadoenum'), nullable=False),
    sa.Column('tiempo_respuesta', sa.Integer(), nullable=True),
    sa.Column('especialista_asignado', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('min_tokens', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('auto_derivacion_activa', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_area_asignada', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_area_asignada'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_area_derivada', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('IA_RESPONDIENDO', 'ESPERANDO_HUMANO', 'FINALIZADA', name='estadoconversacionenum'), nullable=False),
    sa.Column('fecha_derivacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_area_derivada'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'IA', 'HUMANO', 'SISTEMA', name='tipomensajeenum'), nullable=False),
    sa.Column('remitente', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('es_derivacion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes')
    op.drop_table('conversaciones')
    op.drop_table('clientes')
    op.drop_table('configuracion_ia')
    op.drop_table('areas')
    # ### end Alembic commands ###
